# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RealDataset.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PdfViewer import PdfViewer
from LabelFile import Ui_LabelFileWindow


class Ui_RealDatasetWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 20, 151, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groups_8 = QtWidgets.QPushButton(self.centralwidget)
        self.groups_8.setGeometry(QtCore.QRect(270, 130, 81, 31))
        self.groups_8.setObjectName("groups_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 141, 16))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 110, 411, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 141, 16))
        self.label_3.setObjectName("label_3")
        self.groups_10 = QtWidgets.QPushButton(self.centralwidget)
        self.groups_10.setGeometry(QtCore.QRect(270, 180, 81, 31))
        self.groups_10.setObjectName("groups_10")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 160, 411, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 190, 141, 16))
        self.label_4.setObjectName("label_4")
        self.groups_11 = QtWidgets.QPushButton(self.centralwidget)
        self.groups_11.setGeometry(QtCore.QRect(270, 230, 81, 31))
        self.groups_11.setObjectName("groups_11")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 240, 141, 16))
        self.label_5.setObjectName("label_5")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(30, 210, 411, 21))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.groups_12 = QtWidgets.QPushButton(self.centralwidget)
        self.groups_12.setGeometry(QtCore.QRect(270, 280, 81, 31))
        self.groups_12.setObjectName("groups_12")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 290, 141, 16))
        self.label_6.setObjectName("label_6")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(30, 260, 411, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(30, 310, 411, 21))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.groups_9 = QtWidgets.QPushButton(self.centralwidget)
        self.groups_9.setGeometry(QtCore.QRect(360, 130, 81, 31))
        self.groups_9.setObjectName("groups_9")
        self.groups_13 = QtWidgets.QPushButton(self.centralwidget)
        self.groups_13.setGeometry(QtCore.QRect(360, 180, 81, 31))
        self.groups_13.setObjectName("groups_13")
        self.groups_14 = QtWidgets.QPushButton(self.centralwidget)
        self.groups_14.setGeometry(QtCore.QRect(360, 230, 81, 31))
        self.groups_14.setObjectName("groups_14")
        self.groups_15 = QtWidgets.QPushButton(self.centralwidget)
        self.groups_15.setGeometry(QtCore.QRect(360, 280, 81, 31))
        self.groups_15.setObjectName("groups_15")
        self.groups_16 = QtWidgets.QPushButton(self.centralwidget)
        self.groups_16.setGeometry(QtCore.QRect(30, 340, 81, 31))
        self.groups_16.setStyleSheet("background-color: rgb(88, 138, 255);")
        self.groups_16.setObjectName("groups_16")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(250, 380, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 472, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        # button click events

        self.groups_8.clicked.connect(self.openPDFViewer)
        self.groups_9.clicked.connect(self.openLabelWindow)

        # button click events over

    # open PDF viewer
    def openPDFViewer(self):
        file_name = QFileDialog.getOpenFileName()
        print(file_name)
        viewer = PdfViewer(file_name[0])

    # open label file window
    def openLabelWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_LabelFileWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Real Dataset"))
        self.groups_8.setText(_translate("MainWindow", "View "))
        self.label_2.setText(_translate("MainWindow", "* indicates labeled file "))
        self.label_3.setText(_translate("MainWindow", "File 1*"))
        self.groups_10.setText(_translate("MainWindow", "View "))
        self.label_4.setText(_translate("MainWindow", "File 2"))
        self.groups_11.setText(_translate("MainWindow", "View "))
        self.label_5.setText(_translate("MainWindow", "File 3"))
        self.groups_12.setText(_translate("MainWindow", "View "))
        self.label_6.setText(_translate("MainWindow", "File 4"))
        self.groups_9.setText(_translate("MainWindow", "Label file"))
        self.groups_13.setText(_translate("MainWindow", "Label file"))
        self.groups_14.setText(_translate("MainWindow", "Label file"))
        self.groups_15.setText(_translate("MainWindow", "Label file"))
        self.groups_16.setText(_translate("MainWindow", "Re-Run"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_RealDatasetWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
